# These are supported funding model platforms

github:
patreon: # Replace with a single Patreon username
open_collective: nest-cloud
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
